In [1]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]],
                      [[1, 2, 3], [4, 5, 6]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

Creating tensors with tf.variable

In [9]:
changeable_tensor = tf.Variable([1, 2])
unchangeable_tensor = tf.constant([1, 2])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [10]:
changeable_tensor[0].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 2], dtype=int32)>

Creating random *tensors*

In [11]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

Shuffle the order of elements in a tensor

In [13]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [14]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled, not_shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [15]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [16]:
tf.ones(shape = (10, 7), dtype="int32")

<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [17]:
tf.zeros(shape = (10, 7), )

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

turing numpy arrays to tensors

In [18]:
import numpy as np

np_A = np.arange(1, 25, dtype="int32")
np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(np_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [20]:
b = tf.constant(A, shape=(6, 4))
b

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [21]:
 b+10

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]], dtype=int32)>

In [22]:
tf.math.multiply(b, 10)

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200],
       [210, 220, 230, 240]], dtype=int32)>

In [23]:
c = tf.constant(np.arange(1, 26), shape=(5, 5))
tf.linalg.matmul(c, c)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])>

In [24]:
c * c

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])>

In [25]:
a = c @ c

In [26]:
a = tf.cast(a, dtype='int32')
a.dtype

tf.int32

In [27]:
tf.reduce_mean(a).numpy()

895

In [28]:
e = tf.constant(np.random.randint(0, 100, size = 50))
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [29]:
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([66, 58, 53, 68, 84, 31, 13, 92, 86, 14, 15, 86, 42, 18, 83, 63, 28,
       42, 62, 26, 57, 54, 53, 56, 74, 96, 42, 97, 74,  1, 21, 15, 85, 51,
       82,  3, 11, 84, 25, 81, 68, 45, 16, 61, 14, 81, 40, 45,  8, 69])>

In [30]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [31]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [32]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2539>

In [33]:
import tensorflow_probability as tfp
# tf.math.reduce_variance(e)
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=780>

In [34]:
tf.math.reduce_std(tf.cast(e, dtype='float32')) # needs float datatype to work

<tf.Tensor: shape=(), dtype=float32, numpy=27.918661>

In [35]:
tf.math.reduce_variance(tf.cast(e, dtype='float32'))  

<tf.Tensor: shape=(), dtype=float32, numpy=779.45166>

In [36]:
tf.argmax(e), tf.argmin(e)

(<tf.Tensor: shape=(), dtype=int64, numpy=27>,
 <tf.Tensor: shape=(), dtype=int64, numpy=29>)

In [37]:
e[3]

<tf.Tensor: shape=(), dtype=int64, numpy=68>

In [38]:
f = tf.random.uniform(shape = (1, 1, 1, 1, 50))
f

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.43438148, 0.6146749 , 0.5367423 , 0.22423398, 0.91530895,
           0.9676719 , 0.47217715, 0.52890515, 0.7099943 , 0.17688608,
           0.5589495 , 0.68595195, 0.0351187 , 0.28501117, 0.75515115,
           0.95377696, 0.26930463, 0.49302006, 0.78735423, 0.02789283,
           0.692991  , 0.1928587 , 0.23390782, 0.3918637 , 0.59185696,
           0.2593832 , 0.8589536 , 0.8012172 , 0.58028364, 0.44788694,
           0.39555168, 0.42362368, 0.7593998 , 0.43275535, 0.17538333,
           0.22989964, 0.68481183, 0.8212849 , 0.3937918 , 0.2164973 ,
           0.9124197 , 0.06822598, 0.9150946 , 0.47290218, 0.28435457,
           0.57837427, 0.17564511, 0.37604094, 0.8504399 , 0.2591642 ]]]]],
      dtype=float32)>

In [39]:
f.shape

TensorShape([1, 1, 1, 1, 50])

In [40]:
f_squeezed = tf.squeeze(f)
f_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.43438148, 0.6146749 , 0.5367423 , 0.22423398, 0.91530895,
       0.9676719 , 0.47217715, 0.52890515, 0.7099943 , 0.17688608,
       0.5589495 , 0.68595195, 0.0351187 , 0.28501117, 0.75515115,
       0.95377696, 0.26930463, 0.49302006, 0.78735423, 0.02789283,
       0.692991  , 0.1928587 , 0.23390782, 0.3918637 , 0.59185696,
       0.2593832 , 0.8589536 , 0.8012172 , 0.58028364, 0.44788694,
       0.39555168, 0.42362368, 0.7593998 , 0.43275535, 0.17538333,
       0.22989964, 0.68481183, 0.8212849 , 0.3937918 , 0.2164973 ,
       0.9124197 , 0.06822598, 0.9150946 , 0.47290218, 0.28435457,
       0.57837427, 0.17564511, 0.37604094, 0.8504399 , 0.2591642 ],
      dtype=float32)>

In [46]:
some_list = [0, 1, 2, 3, 3, 2]
tf.one_hot(some_list, 4, on_value = "Yes", off_value="No")

<tf.Tensor: shape=(6, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes'],
       [b'No', b'No', b'No', b'Yes'],
       [b'No', b'No', b'Yes', b'No']], dtype=object)>

In [47]:
g = tf.range(0, 10)
g

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [48]:
tf.square(g)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [52]:
tf.sqrt(tf.cast(g, dtype="float"))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [58]:
tf.math.log(tf.cast(g, dtype="float32"))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>